import logging
from typing import List, Dict, Any, Optional
from datetime import datetime
from fastapi import HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import text

from app.repositories.base import AbstractWorkOrderRepository

logger = logging.getLogger(__name__)

MAP_FIELDS = {
    "pkWorkOrder": "pk_workorder",
    "wowoCode": "wowo_code",
    "wowoUserStatus": "wowo_user_status",
    "wowoEquipment": "wowo_equipment",
    "wowoJob": "wowo_job",
    "wowoJobType": "wowo_job_type",
    "wowoJobClass": "wowo_job_class",
    "wowoPriority": "wowo_priority",
    "wowoActionEntity": "wowo_action_entity",
    "wowoRequestEntity": "wowo_request_entity",
    "wowoScheduleDate": "wowo_schedule_date",
    "wowoSupervisor": "wowo_supervisor",
    "wowoCostcentre": "wowo_costcentre",
    "wowoTargetDate": "wowo_target_date",
    "wowoStartDate": "wowo_start_date",
    "wowoEndDate": "wowo_end_date",
    "wowoZone": "wowo_zone",
    "wowoFunction": "wowo_function",
    "wowoFeedbackNote": "wowo_feedback_note",
    "wowoEquipmentDescription": "wowo_equipment_description",
    "wowoString1": "wowo_string1",
    "wowoString2": "wowo_string2",
    "wowoString4": "wowo_string4",
    "mdjbDescription": "mdjb_description",
    "mdusDescription": "mdus_description",
    "wowoActionEntityDescription": "wowo_action_entity_description",
    "wowoCostcentreDescription": "wowo_costcentre_description",
    "wowoJobClassDescription": "wowo_job_class_description",
    "wowoJobTypeDescription": "wowo_job_type_description",
    "wowoSupervisorDescription": "wowo_supervisor_description"
}

REVERSE_MAP = {v: k for k, v in MAP_FIELDS.items()}

class LocalSQLWorkOrderRepository(AbstractWorkOrderRepository):
    """Implémentation d'accès aux données via la base de simulation locale coswin_mock."""
    
    def __init__(self, db: Session):
        self.db = db

    def _parse_date(self, date_val: Any) -> Optional[datetime]:
        if not date_val:
            return None
        if isinstance(date_val, datetime):
            return date_val
        try:
            return datetime.fromisoformat(str(date_val).replace("Z", ""))
        except Exception:
            return None

    def _format_date(self, dt: Any) -> Optional[str]:
        if not dt:
            return None
        if isinstance(dt, datetime):
            return dt.isoformat() + "Z"
        return str(dt)

    def _to_db_dict(self, api_dict: Dict[str, Any]) -> Dict[str, Any]:
        """Convertit un dictionnaire d'API (camelCase) en colonnes de base (snake_case)."""
        db_dict = {}
        for api_key, db_col in MAP_FIELDS.items():
            if api_key in api_dict:
                val = api_dict[api_key]
                # Traitement spécial pour les dates
                if db_col in ["wowo_schedule_date", "wowo_target_date", "wowo_start_date", "wowo_end_date"]:
                    db_dict[db_col] = self._parse_date(val)
                else:
                    db_dict[db_col] = val
        return db_dict

    def _to_api_dict(self, row: Any) -> Dict[str, Any]:
        """Convertit une ligne de base de données en dictionnaire compatible avec l'API Coswin."""
        # row peut être un Row SQLAlchemy ou un tuple
        # On construit le dict à partir des clés
        api_dict = {}
        row_dict = row._asdict() if hasattr(row, "_asdict") else dict(row)
        
        for db_col, api_key in REVERSE_MAP.items():
            if db_col in row_dict:
                val = row_dict[db_col]
                if db_col in ["wowo_schedule_date", "wowo_target_date", "wowo_start_date", "wowo_end_date"]:
                    api_dict[api_key] = self._format_date(val)
                else:
                    api_dict[api_key] = val
        return api_dict

    def _ensure_dependencies(self, db_dict: Dict[str, Any]) -> None:
        """Méthode d'auto-correction pour insérer les dépendances manquantes dans coswin_mock."""
        # 1. Vérifier et créer la Catégorie
        cat = db_dict.get("wowo_job_class")
        if cat:
            exists = self.db.execute(text("SELECT 1 FROM dbo.category WHERE mdct_code = :code"), {"code": cat}).fetchone()
            if not exists:
                self.db.execute(text("INSERT INTO dbo.category (mdct_code, mdct_description) VALUES (:code, :desc)"), 
                                {"code": cat, "desc": db_dict.get("wowo_job_class_description") or "Autogenerated Job Class"})
        
        # 2. Zone
        zone = db_dict.get("wowo_zone")
        if zone:
            exists = self.db.execute(text("SELECT 1 FROM dbo.zone WHERE mdzo_code = :code"), {"code": zone}).fetchone()
            if not exists:
                self.db.execute(text("INSERT INTO dbo.zone (mdzo_code, mdzo_description) VALUES (:code, :desc)"), 
                                {"code": zone, "desc": "Autogenerated Zone"})
                                
        # 3. Entities
        for ent in [db_dict.get("wowo_action_entity"), db_dict.get("wowo_request_entity")]:
            if ent:
                exists = self.db.execute(text("SELECT 1 FROM dbo.entity WHERE chen_code = :code"), {"code": ent}).fetchone()
                if not exists:
                    self.db.execute(text("INSERT INTO dbo.entity (chen_code, chen_description, chen_entity_type, chen_level) VALUES (:code, :desc, 'AUTOGEN', 1)"), 
                                    {"code": ent, "desc": "Autogenerated Entity"})

        # 4. Costcentre
        cc = db_dict.get("wowo_costcentre")
        if cc:
            exists = self.db.execute(text("SELECT 1 FROM dbo.costcentre WHERE mdcc_code = :code"), {"code": cc}).fetchone()
            if not exists:
                self.db.execute(text("INSERT INTO dbo.costcentre (mdcc_code, mdcc_description) VALUES (:code, :desc)"), 
                                {"code": cc, "desc": db_dict.get("wowo_costcentre_description") or "Autogenerated Costcentre"})

        # 5. User / Supervisor
        usr = db_dict.get("wowo_supervisor")
        if usr:
            exists = self.db.execute(text("SELECT 1 FROM dbo.coswin_user WHERE cwcu_code = :code"), {"code": usr}).fetchone()
            if not exists:
                self.db.execute(text("INSERT INTO dbo.coswin_user (cwcu_code, cwcu_signature) VALUES (:code, :sig)"), 
                                {"code": usr, "sig": db_dict.get("wowo_supervisor_description") or "Autogenerated User"})

        # 6. Equipment
        eq = db_dict.get("wowo_equipment")
        if eq:
            exists = self.db.execute(text("SELECT 1 FROM dbo.equipment WHERE ereq_code = :code"), {"code": eq}).fetchone()
            if not exists:
                self.db.execute(
                    text("""
                        INSERT INTO dbo.equipment (
                            ereq_code, ereq_description, ereq_category, ereq_zone, ereq_entity, ereq_function, ereq_costcentre
                        ) VALUES (
                            :code, :desc, :cat, :zone, :ent, :fn, :cc
                        )
                    """),
                    {
                        "code": eq,
                        "desc": db_dict.get("wowo_equipment_description") or "Autogenerated Equipment",
                        "cat": cat or "POSTE",
                        "zone": zone or "DAKAR",
                        "ent": db_dict.get("wowo_request_entity") or "DTAE",
                        "fn": db_dict.get("wowo_function") or "AUTOGEN",
                        "cc": cc or "DD304"
                    }
                )

    async def get_all_workorders(
        self,
        scope: str = "mine",
        supervisor_code: Optional[str] = None,
        request_entity: Optional[str] = None,
        exclude_closed: bool = True,
        pagination_context: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Récupère les ordres de travail locaux, avec tentative de synchronisation depuis l'API Coswin."""
        has_more = False
        next_token = None
        
        # 1. Tenter d'importer la liste depuis Coswin API pour enrichir la base locale
        try:
            from app.repositories.coswin_api import CoswinAPIWorkOrderRepository
            coswin_repo = CoswinAPIWorkOrderRepository()
            
            # Fetch remote list
            remote_res = await coswin_repo.get_all_workorders(
                scope=scope,
                supervisor_code=supervisor_code,
                request_entity=request_entity,
                exclude_closed=exclude_closed,
                pagination_context=pagination_context
            )
            
            has_more = remote_res.get("hasMore", False)
            next_token = remote_res.get("paginationContext")
            
            remote_workorders = remote_res.get("workorders", [])
            logger.info(f"Dynamic caching: fetched {len(remote_workorders)} remote OTs to sync.")
            
            # Upsert each fetched OT in local DB (without sub-resources to keep it fast)
            for wowo in remote_workorders:
                code = str(wowo.get("wowoCode"))
                if not code:
                    continue
                
                # Check if exists locally
                local_exists = self.db.execute(
                    text("SELECT 1 FROM dbo.workorder WHERE wowo_code = :code"),
                    {"code": int(code)}
                ).fetchone()
                
                db_dict = self._to_db_dict(wowo)
                if "pk_workorder" in db_dict:
                    del db_dict["pk_workorder"]
                self._ensure_dependencies(db_dict)
                
                if local_exists:
                    # Update (without wowo_code)
                    if "wowo_code" in db_dict:
                        del db_dict["wowo_code"]
                    set_clause = ", ".join([f"{k} = :{k}" for k in db_dict.keys()])
                    sql = f"UPDATE dbo.workorder SET {set_clause} WHERE wowo_code = :target_code"
                    self.db.execute(text(sql), {**db_dict, "target_code": int(code)})
                else:
                    # Insert
                    cols = ", ".join(db_dict.keys())
                    placeholders = ", ".join([f":{k}" for k in db_dict.keys()])
                    sql = f"INSERT INTO dbo.workorder ({cols}) VALUES ({placeholders})"
                    self.db.execute(text(sql), db_dict)
            
            self.db.commit()
            
        except Exception as e:
            logger.warning(f"Failed to fetch/sync from Coswin API (offline mode fallback): {e}")
            
        # 2. Query from local DB
        sql = "SELECT * FROM dbo.workorder WHERE 1=1"
        params = {}
        
        if scope == "mine" and supervisor_code:
            sql += " AND wowo_supervisor = :supervisor_code"
            params["supervisor_code"] = str(supervisor_code)
        elif scope == "service" and request_entity:
            sql += " AND UPPER(wowo_request_entity) = UPPER(:request_entity)"
            params["request_entity"] = str(request_entity)
            
        if exclude_closed:
            sql += " AND UPPER(wowo_user_status) != 'CL'"
            
        sql += " ORDER BY wowo_code DESC"
        
        rows = self.db.execute(text(sql), params).fetchall()
        matched = [self._to_api_dict(row) for row in rows]
        
        logger.info(f"LocalRepo: get_all_workorders renvoie {len(matched)} OT.")
        return {
            "workorders": matched,
            "paginationContext": next_token,
            "hasMore": has_more,
        }

    async def _ensure_cloned(self, code: str) -> None:
        """S'assure que l'OT et ses sous-ressources sont clonés localement depuis Senelec."""
        # 1. Vérifier si l'OT existe localement et si ses sous-ressources sont marquées comme clonées
        sql = "SELECT wowo_string4 FROM dbo.workorder WHERE wowo_code = :code"
        row = self.db.execute(text(sql), {"code": int(code)}).fetchone()
        
        ot_exists = row is not None
        cloned_sub = False
        
        if ot_exists:
            cloned_sub = row[0] == "CLONED"
            
        # 2. Si l'OT n'existe pas localement ou si ses sous-ressources ne sont pas clonées
        if not ot_exists or not cloned_sub:
            try:
                from app.repositories.coswin_api import CoswinAPIWorkOrderRepository
                coswin_repo = CoswinAPIWorkOrderRepository()
                
                # Fetch main OT from Coswin if not exists
                if not ot_exists:
                    logger.info(f"Dynamic caching: Fetching main OT {code} from Senelec...")
                    remote_ot = await coswin_repo.get_workorder_by_code(code)
                    if remote_ot:
                        db_dict = self._to_db_dict(remote_ot)
                        if "pk_workorder" in db_dict:
                            del db_dict["pk_workorder"]
                        self._ensure_dependencies(db_dict)
                        # Mark as CLONED so we don't repeat this
                        db_dict["wowo_string4"] = "CLONED"
                        
                        cols = ", ".join(db_dict.keys())
                        placeholders = ", ".join([f":{k}" for k in db_dict.keys()])
                        ins_sql = f"INSERT INTO dbo.workorder ({cols}) VALUES ({placeholders})"
                        self.db.execute(text(ins_sql), db_dict)
                        self.db.commit()
                        ot_exists = True
                
                # If OT exists locally now, clone its sub-resources
                if ot_exists:
                    logger.info(f"Dynamic caching: Fetching sub-resources for OT {code} from Senelec...")
                    
                    # 1. Operations (étapes)
                    try:
                        ops = await coswin_repo.get_operations_by_workorder(code)
                        self.db.execute(text("DELETE FROM dbo.workorder_operation WHERE wowo_code = :code"), {"code": int(code)})
                        for op in ops:
                            self.db.execute(
                                text("INSERT INTO dbo.workorder_operation (wowo_code, operation_code, description, duration) VALUES (:wowo_code, :op_code, :desc, :duration)"),
                                {
                                    "wowo_code": int(code),
                                    "op_code": op.get("operationCode") or "OP_REM",
                                    "desc": op.get("opopDescription") or op.get("opopJobDescription") or "Opération",
                                    "duration": float(op.get("duration") or 1.0)
                                }
                            )
                    except Exception as e:
                        logger.warning(f"Failed to clone operations: {e}")
                        
                    # 2. Workforce (mains d'œuvre)
                    try:
                        wf = await coswin_repo.get_workforce_by_workorder(code)
                        self.db.execute(text("DELETE FROM dbo.workorder_workforce WHERE wowo_code = :code"), {"code": int(code)})
                        for emp in wf:
                            self.db.execute(
                                text("INSERT INTO dbo.workorder_workforce (wowo_code, employee_code, employee_name, hours_planned, hours_spent) VALUES (:wowo_code, :emp_code, :emp_name, :planned, :spent)"),
                                {
                                    "wowo_code": int(code),
                                    "emp_code": emp.get("reemCode") or emp.get("woeaEmployee") or "5286",
                                    "emp_name": emp.get("reemDescription") or emp.get("woeaResource") or "Intervenant",
                                    "planned": float(emp.get("woeaPlannedHours") or 0.0),
                                    "spent": float(emp.get("woefActualHours") or 0.0)
                                }
                            )
                    except Exception as e:
                        logger.warning(f"Failed to clone workforce: {e}")
                        
                    # 3. Feedbacks/Documents (commentaires)
                    try:
                        comments = await coswin_repo.get_documents_by_workorder(code)
                        self.db.execute(text("DELETE FROM dbo.workorder_comment WHERE wowo_code = :code"), {"code": int(code)})
                        for c in comments:
                            self.db.execute(
                                text("INSERT INTO dbo.workorder_comment (wowo_code, comment_code, content, author, creation_date) VALUES (:wowo_code, :code, :content, :author, :date)"),
                                {
                                    "wowo_code": int(code),
                                    "code": c.get("reemCode") or c.get("woefEmployee") or "MOCK_USER",
                                    "content": c.get("woefUserStatus") or "Commentaire",
                                    "author": c.get("reemDescription") or "Intervenant",
                                    "date": datetime.now()
                                }
                            )
                    except Exception as e:
                        logger.warning(f"Failed to clone comments: {e}")
                        
                    # 4. Stock / Parts (pièces)
                    try:
                        parts = await coswin_repo.get_parts_by_workorder(code)
                        self.db.execute(text("DELETE FROM dbo.workorder_part WHERE wowo_code = :code"), {"code": int(code)})
                        for p in parts:
                            self.db.execute(
                                text("INSERT INTO dbo.workorder_part (wowo_code, part_code, description, quantity, unit) VALUES (:wowo_code, :part_code, :desc, :qty, :unit)"),
                                {
                                    "wowo_code": int(code),
                                    "part_code": p.get("wosyPart") or p.get("wosyCode") or "PART_REM",
                                    "desc": p.get("wosyDescription") or "Article",
                                    "qty": float(p.get("wosyUsedQuantity") or p.get("wosyQuantity") or 1.0),
                                    "unit": p.get("wosyUnit") or "U"
                                }
                            )
                    except Exception as e:
                        logger.warning(f"Failed to clone parts: {e}")
                        
                    # 5. Attributes (sous-attributs)
                    try:
                        attrs = await coswin_repo.get_attributes_by_workorder(code)
                        self.db.execute(text("DELETE FROM dbo.workorder_attribute WHERE wowo_code = :code"), {"code": int(code)})
                        for a in attrs:
                            self.db.execute(
                                text("INSERT INTO dbo.workorder_attribute (wowo_code, attribute_code, value, description) VALUES (:wowo_code, :code, :val, :desc)"),
                                {
                                    "wowo_code": int(code),
                                    "code": a.get("woatName") or "ATTR_REM",
                                    "val": a.get("woatValue") or "",
                                    "desc": a.get("woatDescription") or "Attribut"
                                }
                            )
                    except Exception as e:
                        logger.warning(f"Failed to clone attributes: {e}")
                        
                    # Update local OT string4 to 'CLONED'
                    self.db.execute(
                        text("UPDATE dbo.workorder SET wowo_string4 = 'CLONED' WHERE wowo_code = :code"),
                        {"code": int(code)}
                    )
                    self.db.commit()
                    
            except Exception as e:
                logger.warning(f"On-demand import failed in _ensure_cloned for OT {code}: {e}")

    async def get_workorder_by_code(self, code: str) -> Dict[str, Any]:
        """Récupère un OT par son code avec import dynamique des données et sous-ressources depuis Senelec."""
        await self._ensure_cloned(code)
        
        sql = "SELECT * FROM dbo.workorder WHERE wowo_code = :code"
        row = self.db.execute(text(sql), {"code": int(code)}).fetchone()
        if not row:
            raise HTTPException(
                status_code=404,
                detail=f"Ordre de travail {code} non trouvé dans la base de simulation et la récupération Senelec a échoué.",
            )
        return self._to_api_dict(row)

    async def create_workorder(self, workorder_data: Dict[str, Any]) -> Dict[str, Any]:
        """Crée un nouvel OT."""
        db_dict = self._to_db_dict(workorder_data)
        if "pk_workorder" in db_dict:
            del db_dict["pk_workorder"]
        
        # S'assurer que le code de l'OT est généré s'il est manquant
        if "wowo_code" not in db_dict:
            max_res = self.db.execute(text("SELECT MAX(wowo_code) FROM dbo.workorder")).fetchone()
            max_code = max_res[0] if max_res and max_res[0] else 2026000000
            db_dict["wowo_code"] = max_code + 1
            
        # Résoudre les contraintes d'intégrité (self-healing)
        self._ensure_dependencies(db_dict)
        
        cols = ", ".join(db_dict.keys())
        placeholders = ", ".join([f":{k}" for k in db_dict.keys()])
        sql = f"INSERT INTO dbo.workorder ({cols}) VALUES ({placeholders})"
        
        self.db.execute(text(sql), db_dict)
        self.db.commit()
        
        return await self.get_workorder_by_code(str(db_dict["wowo_code"]))

    async def update_workorder(self, code: str, workorder_data: Dict[str, Any]) -> Dict[str, Any]:
        """Met à jour un OT existant."""
        # Vérifier l'existence
        await self.get_workorder_by_code(code)
        
        db_dict = self._to_db_dict(workorder_data)
        if "pk_workorder" in db_dict:
            del db_dict["pk_workorder"]
        if "wowo_code" in db_dict:
            del db_dict["wowo_code"]  # Ne pas modifier le code unique
            
        self._ensure_dependencies(db_dict)
        
        set_clause = ", ".join([f"{k} = :{k}" for k in db_dict.keys()])
        sql = f"UPDATE dbo.workorder SET {set_clause} WHERE wowo_code = :target_code"
        
        params = {**db_dict, "target_code": int(code)}
        self.db.execute(text(sql), params)
        self.db.commit()
        
        return await self.get_workorder_by_code(code)

    async def delete_workorder(self, code: str) -> Dict[str, Any]:
        """Supprime un OT."""
        await self.get_workorder_by_code(code)
        
        sql = "DELETE FROM dbo.workorder WHERE wowo_code = :code"
        self.db.execute(text(sql), {"code": int(code)})
        self.db.commit()
        
        return {"success": True, "message": f"Ordre de travail {code} supprime avec succes"}

    # ========== EQUIPMENT & LOCATIONS ==========
    async def get_all_equipment(self) -> List[Dict[str, Any]]:
        rows = self.db.execute(text("SELECT * FROM dbo.equipment")).fetchall()
        res = []
        for r in rows:
            r_dict = r._asdict() if hasattr(r, "_asdict") else dict(r)
            res.append({
                "ereqCode": r_dict.get("ereq_code"),
                "ereqDescription": r_dict.get("ereq_description"),
                "ereqCategory": r_dict.get("ereq_category"),
                "ereqZone": r_dict.get("ereq_zone"),
                "ereqEntity": r_dict.get("ereq_entity"),
                "ereqFunction": r_dict.get("ereq_function"),
                "ereqCostcentre": r_dict.get("ereq_costcentre"),
            })
        return res

    async def get_equipment_by_code(self, code: str) -> Dict[str, Any]:
        row = self.db.execute(text("SELECT * FROM dbo.equipment WHERE ereq_code = :code"), {"code": code}).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail=f"Equipment {code} not found in coswin_mock")
        r_dict = row._asdict() if hasattr(row, "_asdict") else dict(row)
        return {
            "ereqCode": r_dict.get("ereq_code"),
            "ereqDescription": r_dict.get("ereq_description"),
            "ereqCategory": r_dict.get("ereq_category"),
            "ereqZone": r_dict.get("ereq_zone"),
            "ereqEntity": r_dict.get("ereq_entity"),
            "ereqFunction": r_dict.get("ereq_function"),
            "ereqCostcentre": r_dict.get("ereq_costcentre"),
        }

    async def get_all_locations(self) -> List[Dict[str, Any]]:
        return []

    async def get_location_by_code(self, code: str) -> Dict[str, Any]:
        raise HTTPException(status_code=404, detail=f"Location {code} not found in coswin_mock")

    # ========== SUB-RESOURCES (REAL SQL FROM COSWIN_MOCK) ==========
    async def get_operations_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        await self._ensure_cloned(workorder_code)
        rows = self.db.execute(
            text("SELECT pk_operation, wowo_code, operation_code, description, duration FROM dbo.workorder_operation WHERE wowo_code = :code"),
            {"code": workorder_code}
        ).fetchall()
        return [
            {
                "pkOperation": r.pk_operation,
                "wowoCode": r.wowo_code,
                "operationCode": r.operation_code,
                "opopDescription": r.description,
                "opopJobDescription": r.description,
                "duration": r.duration
            }
            for r in rows
        ]

    async def get_workforce_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        await self._ensure_cloned(workorder_code)
        rows = self.db.execute(
            text("SELECT pk_workforce, wowo_code, employee_code, employee_name, hours_planned, hours_spent FROM dbo.workorder_workforce WHERE wowo_code = :code"),
            {"code": workorder_code}
        ).fetchall()
        return [
            {
                "pkWorkforce": r.pk_workforce,
                "wowoCode": r.wowo_code,
                "reemCode": r.employee_code,
                "woeaEmployee": r.employee_code,
                "reemDescription": r.employee_name,
                "woeaResource": r.employee_name,
                "woeaAllocationDate": datetime.now().isoformat() + "Z",
                "woeaIsPlanned": True,
                "woeaPlannedHours": r.hours_planned
            }
            for r in rows
        ]

    async def get_documents_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        # Documents tab in mobile displays feedbacks
        await self._ensure_cloned(workorder_code)
        rows = self.db.execute(
            text("SELECT pk_comment, wowo_code, comment_code, content, author, creation_date FROM dbo.workorder_comment WHERE wowo_code = :code"),
            {"code": workorder_code}
        ).fetchall()
        return [
            {
                "pkComment": r.pk_comment,
                "wowoCode": r.wowo_code,
                "reemDescription": r.author,
                "woefEmployee": r.comment_code,
                "reemCode": r.comment_code,
                "woefStartDate": r.creation_date.isoformat() + "Z" if r.creation_date else None,
                "woefEndDate": r.creation_date.isoformat() + "Z" if r.creation_date else None,
                "woefActualHours": r.hours_planned or 0,
                "woefTotalHours": r.hours_spent or 0,
                "woefUserStatus": r.content
            }
            for r in rows
        ]

    async def get_actions_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return await self.get_operations_by_workorder(workorder_code)

    async def get_allocated_employees_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return await self.get_workforce_by_workorder(workorder_code)

    async def get_employee_feedbacks_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return await self.get_documents_by_workorder(workorder_code)

    async def get_stock_used_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        await self._ensure_cloned(workorder_code)
        rows = self.db.execute(
            text("SELECT pk_part, wowo_code, part_code, description, quantity, unit FROM dbo.workorder_part WHERE wowo_code = :code"),
            {"code": workorder_code}
        ).fetchall()
        return [
            {
                "pkPart": r.pk_part,
                "wowoCode": r.wowo_code,
                "wosyPart": r.part_code,
                "wosyCode": r.part_code,
                "wosyDescription": r.description,
                "wosyUsedQuantity": r.quantity,
                "wosyQuantity": r.quantity,
                "wosyUnit": r.unit
            }
            for r in rows
        ]

    async def get_parts_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return await self.get_stock_used_by_workorder(workorder_code)

    async def get_attributes_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        await self._ensure_cloned(workorder_code)
        rows = self.db.execute(
            text("SELECT pk_attribute, wowo_code, attribute_code, value, description FROM dbo.workorder_attribute WHERE wowo_code = :code"),
            {"code": workorder_code}
        ).fetchall()
        return [
            {
                "pkAttribute": r.pk_attribute,
                "wowoCode": r.wowo_code,
                "woatName": r.attribute_code,
                "woatValue": r.value,
                "woatDescription": r.description
            }
            for r in rows
        ]

    async def get_facilities_used_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return []

    async def get_services_used_by_workorder(self, workorder_code: str) -> List[Dict[str, Any]]:
        return []

    # ========== SUB-RESOURCES CRUD ==========
    async def create_operation(self, workorder_code: str, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("INSERT INTO dbo.workorder_operation (wowo_code, operation_code, description, duration) VALUES (:wowo_code, :op_code, :desc, :duration)"),
            {
                "wowo_code": int(workorder_code),
                "op_code": data.get("operationCode") or data.get("opopDescription") or "OP_MOCK",
                "desc": data.get("opopDescription") or data.get("description") or "Nouvelle opération",
                "duration": float(data.get("duration") or 0.0)
            }
        )
        return {"success": True}

    async def update_operation(self, workorder_code: str, pk: int, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("UPDATE dbo.workorder_operation SET operation_code = :op_code, description = :desc, duration = :duration WHERE pk_operation = :pk"),
            {
                "pk": pk,
                "op_code": data.get("operationCode") or data.get("opopDescription") or "OP_MOCK",
                "desc": data.get("opopDescription") or data.get("description") or "Opération modifiée",
                "duration": float(data.get("duration") or 0.0)
            }
        )
        return {"success": True}

    async def delete_operation(self, workorder_code: str, pk: int) -> Dict[str, Any]:
        self.db.execute(
            text("DELETE FROM dbo.workorder_operation WHERE pk_operation = :pk"),
            {"pk": pk}
        )
        return {"success": True}

    async def create_document(self, workorder_code: str, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("INSERT INTO dbo.workorder_comment (wowo_code, comment_code, content, author, creation_date) VALUES (:wowo_code, :code, :content, :author, :date)"),
            {
                "wowo_code": int(workorder_code),
                "code": data.get("reemCode") or data.get("woefEmployee") or "MOCK_USER",
                "content": data.get("woefUserStatus") or data.get("content") or "Nouveau commentaire",
                "author": data.get("reemDescription") or data.get("author") or "Intervenant",
                "date": datetime.now()
            }
        )
        return {"success": True}

    async def update_document(self, workorder_code: str, pk: int, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("UPDATE dbo.workorder_comment SET content = :content, author = :author WHERE pk_comment = :pk"),
            {
                "pk": pk,
                "content": data.get("woefUserStatus") or data.get("content") or "Commentaire modifié",
                "author": data.get("reemDescription") or data.get("author") or "Intervenant"
            }
        )
        return {"success": True}

    async def delete_document(self, workorder_code: str, pk: int) -> Dict[str, Any]:
        self.db.execute(
            text("DELETE FROM dbo.workorder_comment WHERE pk_comment = :pk"),
            {"pk": pk}
        )
        return {"success": True}

    async def create_workforce(self, workorder_code: str, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("INSERT INTO dbo.workorder_workforce (wowo_code, employee_code, employee_name, hours_planned, hours_spent) VALUES (:wowo_code, :emp_code, :emp_name, :planned, :spent)"),
            {
                "wowo_code": int(workorder_code),
                "emp_code": data.get("reemCode") or data.get("woeaEmployee") or "5286",
                "emp_name": data.get("reemDescription") or data.get("woeaResource") or "Intervenant",
                "planned": float(data.get("woeaPlannedHours") or 0.0),
                "spent": float(data.get("woefActualHours") or 0.0)
            }
        )
        return {"success": True}

    async def update_workforce(self, workorder_code: str, pk: int, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("UPDATE dbo.workorder_workforce SET employee_code = :emp_code, employee_name = :emp_name, hours_planned = :planned, hours_spent = :spent WHERE pk_workforce = :pk"),
            {
                "pk": pk,
                "emp_code": data.get("reemCode") or data.get("woeaEmployee") or "5286",
                "emp_name": data.get("reemDescription") or data.get("woeaResource") or "Intervenant",
                "planned": float(data.get("woeaPlannedHours") or 0.0),
                "spent": float(data.get("woefActualHours") or 0.0)
            }
        )
        return {"success": True}

    async def delete_workforce(self, workorder_code: str, pk: int) -> Dict[str, Any]:
        self.db.execute(
            text("DELETE FROM dbo.workorder_workforce WHERE pk_workforce = :pk"),
            {"pk": pk}
        )
        return {"success": True}

    async def create_part(self, workorder_code: str, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("INSERT INTO dbo.workorder_part (wowo_code, part_code, description, quantity, unit) VALUES (:wowo_code, :part_code, :desc, :qty, :unit)"),
            {
                "wowo_code": int(workorder_code),
                "part_code": data.get("wosyPart") or data.get("wosyCode") or "PART_MOCK",
                "desc": data.get("wosyDescription") or "Nouvel article",
                "qty": float(data.get("wosyUsedQuantity") or data.get("wosyQuantity") or 1.0),
                "unit": data.get("wosyUnit") or "U"
            }
        )
        return {"success": True}

    async def update_part(self, workorder_code: str, pk: int, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("UPDATE dbo.workorder_part SET part_code = :part_code, description = :desc, quantity = :qty, unit = :unit WHERE pk_part = :pk"),
            {
                "pk": pk,
                "part_code": data.get("wosyPart") or data.get("wosyCode") or "PART_MOCK",
                "desc": data.get("wosyDescription") or "Article modifié",
                "qty": float(data.get("wosyUsedQuantity") or data.get("wosyQuantity") or 1.0),
                "unit": data.get("wosyUnit") or "U"
            }
        )
        return {"success": True}

    async def delete_part(self, workorder_code: str, pk: int) -> Dict[str, Any]:
        self.db.execute(
            text("DELETE FROM dbo.workorder_part WHERE pk_part = :pk"),
            {"pk": pk}
        )
        return {"success": True}

    async def create_attribute(self, workorder_code: str, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("INSERT INTO dbo.workorder_attribute (wowo_code, attribute_code, value, description) VALUES (:wowo_code, :code, :val, :desc)"),
            {
                "wowo_code": int(workorder_code),
                "code": data.get("woatName") or "ATTR_MOCK",
                "val": data.get("woatValue") or "VAL_MOCK",
                "desc": data.get("woatDescription") or "Description"
            }
        )
        return {"success": True}

    async def update_attribute(self, workorder_code: str, pk: int, data: Dict[str, Any]) -> Dict[str, Any]:
        self.db.execute(
            text("UPDATE dbo.workorder_attribute SET attribute_code = :code, value = :val, description = :desc WHERE pk_attribute = :pk"),
            {
                "pk": pk,
                "code": data.get("woatName") or "ATTR_MOCK",
                "val": data.get("woatValue") or "VAL_MOCK",
                "desc": data.get("woatDescription") or "Description"
            }
        )
        return {"success": True}

    async def delete_attribute(self, workorder_code: str, pk: int) -> Dict[str, Any]:
        self.db.execute(
            text("DELETE FROM dbo.workorder_attribute WHERE pk_attribute = :pk"),
            {"pk": pk}
        )
        return {"success": True}
